### ISSUE TITLE
Fields are not Found

### ISSUE THREAD

**Issue by goschtl** [Bouke/docx-mailmerge#47]
Hi, i have a Docx with a bunch of Textfields but they are not found.

In the XML they have this structure:

<w:r w:rsidRPr="00943219"><w:rPr><w:sz w:val="18"/></w:rPr><w:fldChar w:fldCharType="begin"><w:ffData><w:name w:val="Text19"/><w:enabled/><w:calcOnExit w:val="0"/><w:textInput><w:maxLength w:val="56"/></w:textInput></w:ffData></w:fldChar></w:r>

any idea how to deal with them?

Thanks in advance.
Christian

**Comment by Bouke** [comment]
This library works with MailMerge fields, not with textfields. You could re-use some of this library's code if you need to work with such fields.
