### ISSUE TITLE
Package broken/old when installing with pip

### ISSUE THREAD

**Issue by toabi** [Bouke/docx-mailmerge#53]
## Expected Behavior
Installing the package with pip gives me the most current version

## Current Behavior
When using the pip installed version, I get an `AttributeError: 'MailMerge' object has no attribute 'merge_templates'`. Even though it says that should be v0.4.*

## Steps to Reproduce (for bugs)
1. Download with pip into venv
2. Call a newer method (e.g. merge_templates)

**Comment by sliverc** [comment]
This hasn't been released yet. And documentation for [version 0.4.0](https://github.com/Bouke/docx-mailmerge/tree/0.4.0) also doesn't state this method.

I guess for now you need to install directly from master to use this feature until new version is released.

@Bouke Would you have time to release a new version?

**Comment by Bouke** [comment]
I've just released 0.5.0.
