### ISSUE TITLE
from mailmerge import MailMerge gives an error.

### ISSUE THREAD

**Issue by petey8** [Bouke/docx-mailmerge#58]
I have the latest version of python installed on my macOS and installed the latest docx-mailmerge via the terminal but keep getting this error when trying to import it in my python shell:

>>> from mailmerge import MailMerge
Traceback (most recent call last):
  File "<pyshell#38>", line 1, in <module>
    from mailmerge import MailMerge
ImportError: cannot import name 'MailMerge' from 'mailmerge' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailmerge/__init__.py)

I think this is an easy to fix error, but I can't figure out what the problem is.. I'm new to python so any advice would be appreciated!!

Thanks!

**Comment by moriartynz** [comment]
Yes, I second and confirm this problem. I'm also getting this error:
ImportError: cannot import name 'MailMerge' from 'mailmerge'

I installed mailmerge using: pip install docx-mailmerge
in a python 3.7 environment on Windows x64

**Comment by MaciekZar** [comment]
I had this problem and I found two possible solutions: 

1. As user scanny  [mentioned](https://github.com/python-openxml/python-docx/issues/41): 

> _For whoever might find this on search, this error is raised when trying to use the python-docx v0.3.0+ API on docx v0.2.x or prior versions.
> 
> The solution, assuming you want to use the newer version, is to uninstall the docx package and install python-pptx, perhaps something like this:
> 
> $ pip uninstall docx
> $ pip install python-docx_

2. And probably similar issue (that worked for me): 
$ pip uninstall mailmerge
$ pip install docx-mailmerge 

Hope it helps

**Comment by WeidnersApps** [comment]
Nothing works for me, is there any other solution?

**Comment by KirtiDahiya** [comment]
Hi WeidnersApps, Did you find the solution?

**Comment by joaoe** [comment]
This bit me because I ran `pip install mailmerge` instead of `pip install docx-mailmerge`. Make sure you have the correct package installed.

**Comment by brenodiogo** [comment]
worked for me.

pip uninstall mailmerge
pip install docx-mailmerge

then run your script:

python script.py

**Comment by lodebosmans** [comment]
Nothing works for me as well.. I'm using PyCharm to run the code.

> Traceback (most recent call last):
>   File "C:/Users/Lode/PycharmProjects/WestFitMutualiteit/WestFitMutualiteit.py", line 2, in <module>
>     from mailmerge import MailMerge
> ModuleNotFoundError: No module named 'mailmerge'

**Comment by brenodiogo** [comment]
sounds like an environment issue. make sure PyCharm is using the correct python interpreter.

import sys
print(sys.version)

for path in sys.path:
    print(path)

this should print a list of directories where Python searches for modules.

if you navigate these directories, you should be able to find mailmerge there. if PyCharm is using the wrong python interpreter, [you need to point it to the correct one](https://www.jetbrains.com/help/pycharm-edu/configuring-language-interpreter.html#interpreter-name-change)

**Comment by lodebosmans** [comment]
> 
> 
> sounds like an environment issue. make sure PyCharm is using the correct python interpreter.
> 
> import sys
> print(sys.version)
> 
> for path in sys.path:
> print(path)
> 
> this should print a list of directories where Python searches for modules.
> 
> if you navigate these directories, you should be able to find mailmerge there. if PyCharm is using the wrong python interpreter, [you need to point it to the correct one](https://www.jetbrains.com/help/pycharm-edu/configuring-local-python-interpreters.html)

Seems like you are right. Had to do some more configuring of PyCharm. Works perfectly now. Thanks for the support!

**Comment by joaoe** [comment]
So, this is not an issue with mailmerge, and can be closed.

**Comment by mattborhan** [comment]
Hi Bouke and Joaoe,

I don't think it's an environment issue. I'm using Jupyter on Azure notebooks. I get the same error and none of the suggested solutions worked by far. I appreciate if you reopen the post so we can benefit from other people's recommendations.

Thanks,
M

**Comment by danerlt** [comment]
> I had this problem and I found two possible solutions:
> 
> 1. As user scanny  [mentioned](https://github.com/python-openxml/python-docx/issues/41):
> 
> > _For whoever might find this on search, this error is raised when trying to use the python-docx v0.3.0+ API on docx v0.2.x or prior versions.
> > The solution, assuming you want to use the newer version, is to uninstall the docx package and install python-pptx, perhaps something like this:
> > $ pip uninstall docx
> > $ pip install python-docx_
> 
> 1. And probably similar issue (that worked for me):
>    $ pip uninstall mailmerge
>    $ pip install docx-mailmerge
> 
> Hope it helps

Thanks
