### ISSUE TITLE
Remove .icloud files

### ISSUE THREAD

**Issue by mjmare** [Bouke/docx-mailmerge#59]
## Current Behavior
When I have installed docx-mailmerge into a virtualenv that is situated in my Dropbox I get warnings from Dropbox that .icloud files were found. Apparently that may cause problems and Dropbox prompts to get rid of these files. 

The files concerned are:
…/venv3/lib/python3.7/site-packages/docx_mailmerge-0.4.0.dist-info/.pbr.json.icloud
…/venv3/lib/python3.7/site-packages/docx_mailmerge-0.4.0.dist-info/.SOURCES.txt.icloud

I do not see this with other packages.

## Steps to Reproduce (for bugs)
Create virtualenv on Dropbox
Install docx-mailmerge
Wait for email from Dropbox (in about a day)

* Python version: MacOS 10.13.6, python 3.7
* docx-mailmerge version: 0.4

The mail from Dropbox:
<img width="596" alt="screen shot 2018-08-21 at 10 55 18" src="https://user-images.githubusercontent.com/1711378/44391669-c2cc9200-a530-11e8-87fe-29ca0f54eadc.png">
<img width="626" alt="screen shot 2018-08-21 at 10 55 24" src="https://user-images.githubusercontent.com/1711378/44391668-c2cc9200-a530-11e8-8343-e68a1fd4b27d.png">

**Comment by Bouke** [comment]
Doesn't happen with 0.5.0. I store my development folder on iCloud, and as a result iCloud will sometimes create those placeholder files (.iCloud). I'm not sure what I can do to prevent this, other than changing my workflow.
